name: Scrape Competitor Promotions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 selenium undetected-chromedriver setuptools

      - name: Run Scraper
        run: |
          # Modifikasi skrip untuk menggunakan driver yang disediakan oleh robot GitHub
          sed -i "s/service = Service(executable_path='chromedriver.exe')/service = webdriver.chrome.service.Service()/g" scraper.py
          sed -i "s/service = webdriver.chrome.service.Service()/import undetected_chromedriver as uc\n    service = webdriver.chrome.service.Service()/g" scraper.py
          sed -i "s/driver = uc.Chrome(options=options)/driver = uc.Chrome(options=options, service=service)/g" scraper.py
          sed -i "s/options = uc.ChromeOptions()/options = uc.ChromeOptions()\n    options.add_argument('--no-sandbox')\n    options.add_argument('--disable-dev-shm-usage')/g" scraper.py
          python scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add promotions.json
          git diff --staged --quiet || (git commit -m "Update promotions data" && git push)
